# Generated by Django 2.2.6 on 2019-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='matric',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='matric'),
        ),
    ]
